In [17]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
df = pd.read_excel(r"E:\Data Science by SRK\Machine_learning\project\Taxi_price_prediction_xgboost\cleaned_Taxi_Price_data.xlsx")

In [19]:
df

     Trip_Distance_km  Per_Km_Rate  Trip_Price
0            3.013081     0.800000     36.2624
1            3.634159     1.210000     52.9032
2            3.444576     0.510000     36.4698
3            3.339003     0.630000     15.6180
4            2.265921     1.710000     60.2028
..                ...          ...         ...
946          1.870263     0.620000     34.4049
947          3.849083     0.610000     62.1295
948          2.163323     1.780000     33.1236
949          3.882800     0.820000     61.2090
950          3.171784     1.229934     45.4437

[951 rows x 3 columns]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 951 entries, 0 to 950
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Trip_Distance_km  951 non-null    float64
 1   Per_Km_Rate       951 non-null    float64
 2   Trip_Price        951 non-null    float64
dtypes: float64(3)
memory usage: 22.4 KB

In [21]:
X = df.drop(columns = ['Trip_Price'])
y = df['Trip_Price']

# TRAIN_TEST_SPLIT

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 5)

In [23]:
X_train

     Trip_Distance_km  Per_Km_Rate
352          1.702928     1.780000
899          2.164472     1.229934
178          3.330417     1.320000
438          3.894877     0.950000
795          4.848490     0.850000
..                ...          ...
400          3.339003     1.420000
118          3.132446     0.760000
701          3.737908     1.800000
206          3.775286     0.940000
867          3.483699     0.880000

[760 rows x 2 columns]

# Modelling : Polynomial Regression

**Incresing higher degree of input variable & Applying linear regression**

In [24]:
# ALL STEPS IN ONE CELL   (DEGREE = 2)


# Increasing degree of input variable : 
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter =  PolynomialFeatures(degree = 2, include_bias = False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))


# Create model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_poly, y_train)

#("Intercept : ",model.intercept_)
#print("coefficients : ", model.coef_)

# Prediction on Train data
ypred_train = model.predict(X_train_poly)


# EVALUATION on Train data
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#print("Train RMSE : ", np.sqrt(mean_squared_error(y_train, ypred_train)))
print("Train R2 : ", r2_score(y_train, ypred_train))
print("Cross_validation_score : ", cross_val_score(model, X_train_poly, y_train, cv= 5).mean())


# Variable Significance
# ASSUME HERE ALL VARIABLES ARE SIGNIFICANT


# Data preprocessing n test data
X_test_poly = pd.DataFrame(polynomial_converter.transform(X_test))


# prediction on test data
ypred_test = model.predict(X_test_poly)


# Evaluation on Test data
print("Test R2 : ", r2_score(y_test, ypred_test))

Train R2 :  0.7183809840498853
Cross_validation_score :  0.6786125855190571
Test R2 :  0.7271435535562486

In [25]:
# ALL STEPS IN ONE CELL   (DEGREE = 3)


# Increasing degree of input variable : 
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter =  PolynomialFeatures(degree = 3, include_bias = False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))


# Create model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_poly, y_train)

#("Intercept : ",model.intercept_)
#print("coefficients : ", model.coef_)

# Prediction on Train data
ypred_train = model.predict(X_train_poly)


# EVALUATION on Train data
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#print("Train RMSE : ", np.sqrt(mean_squared_error(y_train, ypred_train)))
print("Train R2 : ", r2_score(y_train, ypred_train))
print("Cross_validation_score : ", cross_val_score(model, X_train_poly, y_train, cv= 5).mean())


# Variable Significance
# ASSUME HERE ALL VARIABLES ARE SIGNIFICANT


# Data preprocessing n test data
X_test_poly = pd.DataFrame(polynomial_converter.transform(X_test))


# prediction on test data
ypred_test = model.predict(X_test_poly)


# Evaluation on Test data
print("Test R2 : ", r2_score(y_test, ypred_test))

Train R2 :  0.8323861790838726
Cross_validation_score :  0.7904981794182863
Test R2 :  0.8595709250858803

In [26]:
# ALL STEPS IN ONE CELL   (DEGREE = 4)


# Increasing degree of input variable : 
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter =  PolynomialFeatures(degree = 4, include_bias = False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))


# Create model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_poly, y_train)

#("Intercept : ",model.intercept_)
#print("coefficients : ", model.coef_)

# Prediction on Train data
ypred_train = model.predict(X_train_poly)


# EVALUATION on Train data
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#print("Train RMSE : ", np.sqrt(mean_squared_error(y_train, ypred_train)))
print("Train R2 : ", r2_score(y_train, ypred_train))
print("Cross_validation_score : ", cross_val_score(model, X_train_poly, y_train, cv= 5).mean())


# Variable Significance
# ASSUME HERE ALL VARIABLES ARE SIGNIFICANT


# Data preprocessing n test data
X_test_poly = pd.DataFrame(polynomial_converter.transform(X_test))


# prediction on test data
ypred_test = model.predict(X_test_poly)


# Evaluation on Test data
print("Test R2 : ", r2_score(y_test, ypred_test))

Train R2 :  0.8486156211575936
Cross_validation_score :  0.801732716404312
Test R2 :  0.8831374372783753

**(Degree = 4) : NO overfitting problem MEANS THIS IS BEST MODEL**