In [48]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [49]:
df = pd.read_csv(r"E:\Data Science by SRK\Machine_learning\project\Medical Insurance Costs Dataset\cleaned_dataset_medical_cost_insurance.csv")

In [50]:
df

      age  gender     bmi  children  smoker      charges
0      19       0  27.900         0       1  16884.92400
1      18       1  33.770         1       0   1725.55230
2      28       1  33.000         3       0   4449.46200
3      33       1  22.705         0       0  21984.47061
4      32       1  28.880         0       0   3866.85520
...   ...     ...     ...       ...     ...          ...
1332   50       1  30.970         3       0  10600.54830
1333   18       0  31.920         0       0   2205.98080
1334   18       0  36.850         0       0   1629.83350
1335   21       0  25.800         0       0   2007.94500
1336   61       0  29.070         0       1  29141.36030

[1337 rows x 6 columns]

In [51]:
X = df[['age', 'gender', 'bmi', 'children', 'smoker']]

y = df['charges']

**TRAIN_TEST_SPLIT**

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 9)

In [53]:
X_train

      age  gender     bmi  children  smoker
1331   52       0  44.700         3       0
665    49       1  28.700         1       0
1154   36       0  22.135         3       0
618    55       0  37.100         0       0
9      60       0  25.840         0       0
...   ...     ...     ...       ...     ...
56     58       0  31.825         2       0
501    43       1  26.030         0       0
638    56       1  33.660         4       0
348    36       0  29.920         1       0
382    55       1  33.000         0       0

[1069 rows x 5 columns]

# Modelling : Polynomial Regression

**Incresing higher degree of input variable & Applying linear regression**

In [54]:
from sklearn.preprocessing import PolynomialFeatures

polynomial_converter =  PolynomialFeatures(degree = 2, include_bias = False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))

In [55]:
X_train_poly

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,52.0,0.0,44.700,3.0,0.0,2704.0,0.0,2324.40,156.0,0.0,0.0,0.00,0.0,0.0,1998.090000,134.100,0.0,9.0,0.0,0.0
1,49.0,1.0,28.700,1.0,0.0,2401.0,49.0,1406.30,49.0,0.0,1.0,28.70,1.0,0.0,823.690000,28.700,0.0,1.0,0.0,0.0
2,36.0,0.0,22.135,3.0,0.0,1296.0,0.0,796.86,108.0,0.0,0.0,0.00,0.0,0.0,489.958225,66.405,0.0,9.0,0.0,0.0
3,55.0,0.0,37.100,0.0,0.0,3025.0,0.0,2040.50,0.0,0.0,0.0,0.00,0.0,0.0,1376.410000,0.000,0.0,0.0,0.0,0.0
4,60.0,0.0,25.840,0.0,0.0,3600.0,0.0,1550.40,0.0,0.0,0.0,0.00,0.0,0.0,667.705600,0.000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1064,58.0,0.0,31.825,2.0,0.0,3364.0,0.0,1845.85,116.0,0.0,0.0,0.00,0.0,0.0,1012.830625,63.650,0.0,4.0,0.0,0.0
1065,43.0,1.0,26.030,0.0,0.0,1849.0,43.0,1119.29,0.0,0.0,1.0,26.03,0.0,0.0,677.560900,0.000,0.0,0.0,0.0,0.0
1066,56.0,1.0,33.660,4.0,0.0,3136.0,56.0,1884.96,224.0,0.0,1.0,33.66,4.0,0.0,1132.995600,134.640,0.0,16.0,0.0,0.0
1067,36.0,0.0,29.920,1.0,0.0,1296.0,0.0,1077.12,36.0,0.0,0.0,0.00,0.0,0.0,895.206400,29.920,0.0,1.0,0.0,0.0
1068,55.0,1.0,33.000,0.0,0.0,3025.0,55.0,1815.00,0.0,0.0,1.0,33.00,0.0,0.0,1089.000000,0.000,0.0,0.0,0.0,0.0

In [56]:
# ALL STEPS IN ONE CELL   (DEGREE = 2)


# Increasing degree of input variable : 
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter =  PolynomialFeatures(degree = 2, include_bias = False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))


# Create model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_poly, y_train)

#("Intercept : ",model.intercept_)
#print("coefficients : ", model.coef_)

# Prediction on Train data
ypred_train = model.predict(X_train_poly)


# EVALUATION on Train data
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#print("Train RMSE : ", np.sqrt(mean_squared_error(y_train, ypred_train)))
print("Train R2 : ", r2_score(y_train, ypred_train))
print("Cross_validation_score : ", cross_val_score(model, X_train_poly, y_train, cv= 5).mean())


# Variable Significance
# ASSUME HERE ALL VARIABLES ARE SIGNIFICANT


# Data preprocessing n test data
X_test_poly = pd.DataFrame(polynomial_converter.transform(X_test))


# prediction on test data
ypred_test = model.predict(X_test_poly)


# Evaluation on Test data
print("Test R2 : ", r2_score(y_test, ypred_test))

Train R2 :  0.8522384570145585
Cross_validation_score :  0.8445378577404263
Test R2 :  0.8009188353198202

**Degree =2 is good model**

In [57]:
# ALL STEPS IN ONE CELL   (DEGREE = 3)


# Increasing degree of input variable : 
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter =  PolynomialFeatures(degree = 3, include_bias = False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))


# Create model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_poly, y_train)

#("Intercept : ",model.intercept_)
#print("coefficients : ", model.coef_)

# Prediction on Train data
ypred_train = model.predict(X_train_poly)


# EVALUATION on Train data
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#print("Train RMSE : ", np.sqrt(mean_squared_error(y_train, ypred_train)))
print("Train R2 : ", r2_score(y_train, ypred_train))
print("Cross_validation_score : ", cross_val_score(model, X_train_poly, y_train, cv= 5).mean())


# Variable Significance
# ASSUME HERE ALL VARIABLES ARE SIGNIFICANT


# Data preprocessing n test data
X_test_poly = pd.DataFrame(polynomial_converter.transform(X_test))


# prediction on test data
ypred_test = model.predict(X_test_poly)


# Evaluation on Test data
print("Test R2 : ", r2_score(y_test, ypred_test))

Train R2 :  0.8588322482606688
Cross_validation_score :  0.841794321642182
Test R2 :  0.796745163182301

In [58]:
# ALL STEPS IN ONE CELL   (DEGREE = 4)


# Increasing degree of input variable : 
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter =  PolynomialFeatures(degree = 4, include_bias = False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))


# Create model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_poly, y_train)

#("Intercept : ",model.intercept_)
#print("coefficients : ", model.coef_)

# Prediction on Train data
ypred_train = model.predict(X_train_poly)


# EVALUATION on Train data
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#print("Train RMSE : ", np.sqrt(mean_squared_error(y_train, ypred_train)))
print("Train R2 : ", r2_score(y_train, ypred_train))
print("Cross_validation_score : ", cross_val_score(model, X_train_poly, y_train, cv= 5).mean())


# Variable Significance
# ASSUME HERE ALL VARIABLES ARE SIGNIFICANT


# Data preprocessing n test data
X_test_poly = pd.DataFrame(polynomial_converter.transform(X_test))


# prediction on test data
ypred_test = model.predict(X_test_poly)


# Evaluation on Test data
print("Test R2 : ", r2_score(y_test, ypred_test))

Train R2 :  0.8667763621718585
Cross_validation_score :  0.8148038530038029
Test R2 :  0.7947289952467633